### PR TITLE
fix: use default token, document token permissions

### PR DESCRIPTION
**Pull request by EndBug**
Hi, this PR makes the action use the `github.token` default instead of relying on manual env input, and documents required token permissions.

### CODE REVIEW

**Comment by nanoufo** [comment]
Didn't know that the token can be provided using the default input value.
That PR may break the action for users who use the environment variable to pass a token with access to other repositories.
Looks like there are not many such users [if there are any at all], also they should have pinned the action version.
So I am going to accept the PR after compiling & testing.

**Comment by nanoufo** [comment]
Fixed formatting issues in main, rebased & force-pushed this PR.
Manually tested, everything is ok.
Merging now.

**Comment by EndBug** [comment]
Nice, thanks 🚀

**Comment by BenjaminNolan** [comment]
If anyone does need to pass in a token, they just need to change

```
env:
   GITHUB_TOKEN: ${{ secrets.TOKEN_NAME_HERE }}
```

to

```
with:
   github-token: ${{ secrets.TOKEN_NAME_HERE }}
```

:)

**Pull request merged**
